### ISSUE TITLE
Problem with Optifabric and Itembound (Named Custom Items)

### ISSUE THREAD

**Issue by Burgersim** [modmuss50/OptiFabric#100]
Hi, I hope this is the right place to ask this, but I can not get the Custom Items from the Itembound texture pack to work with Optifabric and Optifine 1.14.4 HD U4. I know that you didn't make the resource pack, I was just wondering if custom items should work with optifabric, or if this could just be a bug or not yet implemented feature.

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0

**Comment by Burgersim** [comment]
Ok I updated to the newest Version, also to the newest Fabric Loader Version (in MultiMC) but it still doesn't seem to be working for me, I thought maybe the log could help somehow?

[unfinishedlog.txt](https://github.com/modmuss50/OptiFabric/files/3883034/unfinishedlog.txt)

**Comment by Burgersim** [comment]
Quick Update, I got it to work, although I had to download the resource pack from another site than curseforge apparently, but it seems it was in the end a Problem with the resource pack, not the Optifabric mod, I think, thanks a lot though
